/**
 * This file is autogenerated.
 */

const deployedContracts = {
  31337: {
    WalletGenerator: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_owners",
              type: "address[]",
            },
            {
              internalType: "uint256",
              name: "_requiredSinatures",
              type: "uint256",
            },
          ],
          name: "createNewWallet",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts;
