/**
 * This file is autogenerated.
 */

const deployedContracts = {
  1337: {
    WalletGenerator: {
      address: "0x03642ab89b5418B45268C44123123d84008d0799",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "NotOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address[]",
              name: "owners",
              type: "address[]",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "signaturesRequired",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "walletAddress",
              type: "address",
            },
          ],
          name: "WalletCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "owners",
              type: "address[]",
            },
            {
              internalType: "uint256",
              name: "signaturesRequired",
              type: "uint256",
            },
          ],
          name: "createNewWallet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts;
